# Generated by Django 3.2.15 on 2022-10-23 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='group',
            name='maxparticipants',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='group',
            name='num_participants',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='qendtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant', to='trivia.group'),
        ),
    ]
