# Generated by Django 4.1.2 on 2022-10-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trivia", "0004_quiz_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quiz_group",
                to="trivia.group",
            ),
        ),
    ]
