# Generated by Django 4.1.2 on 2022-10-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trivia", "0005_alter_quiz_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="group",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
