# Generated by Django 4.1.2 on 2022-10-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trivia", "0006_remove_quiz_group_delete_question_delete_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
    ]
