# Generated by Django 4.1.2 on 2022-10-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trivia", "0007_remove_user_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant",
                to="trivia.group",
            ),
        ),
    ]
