# Generated by Django 4.1.2 on 2022-10-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trivia", "0009_quiz_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="group",
        ),
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="participant",
                to="trivia.group",
            ),
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
