# Generated by Django 4.1.2 on 2022-10-26 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trivia", "0010_remove_quiz_group_alter_user_group_delete_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participant",
                to="trivia.group",
            ),
        ),
    ]
