# Generated by Django 3.2.15 on 2022-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0012_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='categoryid',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='categoryname',
            field=models.CharField(default='', max_length=256),
        ),
    ]
