# Generated by Django 3.2.15 on 2022-10-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0014_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='numcompleted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
