# Generated by Django 3.2.15 on 2022-10-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0015_scores_numcompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='maxparticipants',
        ),
        migrations.RemoveField(
            model_name='group',
            name='num_participants',
        ),
        migrations.RemoveField(
            model_name='group',
            name='qendtime',
        ),
    ]
