# Generated by Django 4.1.2 on 2022-10-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trivia", "0016_auto_20221028_1701"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="groupname",
        ),
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
        migrations.RemoveField(
            model_name="user",
            name="score",
        ),
    ]
